name: CI_CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18' 

      - name: Install Node.js dependencies
        run: npm install

      - name: Start Backend Server
        run: |
          npx next dev &
          npx wait-on http://localhost:3000  # Wait for the server to fully start

      - name: Run Tests
        run: python -m unittest discover -s tests
